### ISSUE TITLE
"Publish" token in git

### ISSUE THREAD

**Issue by jku** [sigstore-conformance/extremely-dangerous-public-oidc-beacon#17]
This is attempt 2 at making the token more easily available for users: Github Pages turned out to be unreliable for the required publishing frequency.

Next idea: We could push the token into git (not main branch but an ephemeral one)
* I've got this running in https://github.com/jku/extremely-dangerous-public-oidc-beacon/ (see `current-token` branch)
* Users could then simply download from a URL like https://raw.githubusercontent.com/jku/extremely-dangerous-public-oidc-beacon/current-token/oidc-token.txt ... unfortunately this turns out to be heavily cached as well and may not update for minutes
* so we would have to actually use git to access this in a timely manner
* actions/checkout can do single file sparse checkouts so is almost perfect: unfortunately we have the additional problem that sometimes the token is not valid and we would like to retry a little later...
* maybe we could provide a reusable workflow 'download-token' in extremely-dangerous-public-oidc-beacon or sigstore-conformance that did the dance of sparse-checkout-with-retries-if-token-is-invalid... but it does sound a bit complicated

**Comment by jku** [comment]
> maybe we could provide a reusable workflow 'download-token' in extremely-dangerous-public-oidc-beacon or sigstore-conformance that did the dance of sparse-checkout-with-retries-if-token-is-invalid... but it does sound a bit complicated

Still, there's already multiple projects that need this retry functionality so could as well put it in a reusable workflow:
```
repeat  a few times:
    in a temp dir, do sparse checkout of current-token branch of extremely-dangerous-public-oidc-beacon
    if expiry is at least x seconds away 
        copy token to working dir and break
    else:
        sleep for a while
```

**Comment by woodruffw** [comment]
Publishing in `git` sounds fine to me (hacky, but no less hacky than anything else we've done so far :slightly_smiling_face:).



> * maybe we could provide a reusable workflow 'download-token' in extremely-dangerous-public-oidc-beacon or sigstore-conformance that did the dance of sparse-checkout-with-retries-if-token-is-invalid... but it does sound a bit complicated

I like this idea! Better to have the complication abstracted in a reusable workflow (or full action).

**Comment by jku** [comment]
I made the action (and have tested it for a few days now): it looks ok.

For sigstore-conformance itself we might still want to *not* use the action if the planned staging support goes in: in that case it might make sense to still do the token download in pytest (so both runs of the conformance suite get a fresh token). We can still use IMO simpler download-token.py code there: at least that does not require a GitHub token.
