### ISSUE TITLE
Figure out a better way to keep the beacon alive

### ISSUE THREAD

**Issue by woodruffw** [sigstore-conformance/extremely-dangerous-public-oidc-beacon#4]
The beacon currently runs on a schedule; GitHub Actions disables scheduled workflows after 60 days of repository inactivity.

As a result: if nobody commits to this repo in a 60 day window, the beacon's scheduled job stops running and repos that test using the Sigstore conformance suite begin to fail. For example, the timeout failures in https://github.com/sigstore/sigstore-python/pull/702.

Some ideas:

1. Maybe there's some way to get this repository excluded from the scheduled workflow expiration rule. CC @steiza?
2. Maybe we can "cheese" things here and have a periodic job that also commits to the repo, to keep the workflows active.

**Comment by woodruffw** [comment]
As a resolution here, we'll start with (2).

**Comment by woodruffw** [comment]
Happened again: https://github.com/sigstore/sigstore-conformance/issues/117

**Comment by jku** [comment]
> Maybe we can "cheese" things here and have a periodic job that also commits to the repo

My previous attempt at making the token more easily available via Pages failed (see #8) but I had another idea for that: commiting the current token to git and maybe force pushing a tag/branch that points to the current-token-commit (re-using the tag/branch to avoid polluting git checkouts too much). It sounds like a hack but it might be a two-birds-with-a-single-commit type of hack...

**Comment by woodruffw** [comment]
I like that idea!

(@steiza: do you happen to know if machine commits to a branch count for resetting the workflow  expiration countdown? I know Dependabot commits/PRs do, but that might only be because they get merged by a human.)

**Comment by haydentherapper** [comment]
I ran into this when monitoring the log, because the repository only contains a workflow that never commits. I found https://github.com/marketplace/actions/keepalive-workflow as a potential solution, though I haven't tried it out yet.

**Comment by jku** [comment]
I don't know yet if #17 makes sense but it might accidentally fix this one
